### DISCUSSION TITLE
フィールドのラベル名の文字色の変更方法

### DISCUSSION THREAD

**Discussion by kazuino44** [thinkingreed-inc/F-RevoCRM#808] [Q&A] [answered]
現在の黒色をグレーに変更したいのですが、修正箇所（色の指定箇所）をご教授いただけませんか。

よろしくお願いいたします。

**Comment by Remicck** [comment, marked as answer]
@kazuino44 
![image](https://user-images.githubusercontent.com/3492320/224217217-9cd81997-4580-4d7e-ad95-883c842bd6f4.png)
この部分であってますか？

スクリーンショットですみません。以下で変えられると思います。
![image](https://user-images.githubusercontent.com/3492320/224217389-f2921058-39b3-41b2-835c-319c8fc970df.png)

**Reply by kazuino44** [reply]
ありがとうございます。
はい、その部分になります。

お手数ですが、対象のファイル名も教えていただけませんか。

よろしくお願いいたします。

**Reply by Remicck** [reply]
`/resources/styles.css:243`付近
```css
.detailview-table .fieldLabel .muted,
.recordEditView .fieldLabel .muted,
.summaryView .fieldLabel .muted{
    color: #222;
    font-weight: bold;
}
```
Google ChromeのDeveloperToolsから、スタイルが適用されている対象のファイルがわかりますのでそちらもご確認ください。
※先程のコメントの右の方に、`styles.css?{param}:243` と記載があり、クリックすると対象のファイルが確認できます。
